# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: musiciansname
      POSTGRES_PASSWORD: anilstraining_2022
  web:
    build: .
    container_name: webapp
    depends_on:
      - "db"
    ports:
      - "8085:8080"
networks:
  default:
    name: kopru
    external: true