management:
    security:
        enabled: false
security:
    basic:
        enabled: false
    ignored: /**
spring:
    data:
        jpa:
            repositories:
                bootstrap-mode: default
    datasource:
        url: jdbc:sqlserver://musiciansreposerver.database.windows.net:1433;database=MusiciansRepo;user=musiciansname@musiciansreposerver;password=anilstraining_2022;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    jpa:
        defer-datasource-initialization: true
    security:
        enabled: false
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
        timeout:
            seconds: 900
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"