spring:
    security:
        enabled: true
        user:
            name: admin
            password: adminPassword
        database: postgresql   # change with 'jdbc:postgresql://localhost:5432/ftsdb' for in docker-compose generated postgresql
    datasource:
        url: jdbc:postgresql://ftspostgresqldb.postgres.database.azure.com:5432/postgres?sslmode=require
        username: musiciansname
        password: anilstraining_2022
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"