server:
    port: 8085
security:
    jwt:
        enabled: false
spring:
    flyway:
        url: jdbc:postgresql://localhost:5432/postgres
        user: musiciansname
        password: anilstraining_2022
    jpa:
        hibernate:
            ddl-auto: none
        database: postgresql
    security:
        user:
            name: anil
            password: 123
        database: postgresql
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: musiciansname
        password: anilstraining_2022
        driver-class-name: org.postgresql.Driver
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
        timeout:
            seconds: 900
logging:
    level:
        org:
            springframework:
                security: off
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"
clients:
    blogpage:
        basePath: "http://localhost:8083"
jwt:
    key: ""
    header: "Authorization"
resilience4j:
    circuitbreaker:
        configs:
            default:
                failureRateThreshold: 50
                slidingWindowSize: 3
                waitDurationInOpenState: 10s
                registerHealthIndicator: false
        instances:
            personalpage:
                baseConfig: default
        retry:
            instances:
                personalpage:
                    maxAttempts: 2
                    waitDuration: 10s
