management:
    security:
        enabled: false
security:
    basic:
        enabled: false
    ignored: /**

spring:
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
    datasource:
        url: jdbc:postgresql://ftspostgresqldb.postgres.database.azure.com:5432/postgres?sslmode=require
        username: musiciansname
        password: anilstraining_2022
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"