spring:
    security:
        enabled: false
        user:
            name: admin
            password: adminPassword
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: musiciansname
        password: anilstraining_2022
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
        timeout:
            seconds: 900
logging:
    level:
        org:
            springframework:
                security: DEBUG
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"