spring:
    flyway:
        url: jdbc:postgresql://ftspostgresqldb.postgres.database.azure.com:5432/postgres
        user: musiciansname
        password: anilstraining_2022
    jpa:
        hibernate:
            ddl-auto: none
        database: postgresql
    security:
        enabled: true
        user:
            name: admin
            password: adminPassword
        database: postgresql
    datasource:
        url: jdbc:postgresql://ftspostgresqldb.postgres.database.azure.com:5432/postgres?sslmode=require
        username: musiciansname
        password: anilstraining_2022
        driver-class-name: org.postgresql.Driver
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
        timeout:
            seconds: 900
songs:
    ownedsongs:
        - "Devil In my Town"
    coveredsongs:
        - "Enter Sandman"
        - "Mother"
        - "Seal the Deal"