apiVersion: v1
kind: Service
metadata:
  name: frontendClusterIP
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backendpersonalpageClusterIP
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: backendpersonalpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontendlb
  namespace: goodbyeprophecy
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080