apiVersion: v1
kind: Service
metadata:
  name: frontend-clusterip-svc
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip-service
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backendpersonalpage-clusterip-svc
  namespace: goodbyeprophecy
spec:
  type: ClusterIP
  selector:
    app: backendpersonalpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-svc
  namespace: goodbyeprophecy
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080