apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: nsfeelthesteel
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  replicas: 2
  selector:
    app: backend
  template:
    metadata:
      name: ftsappdeployment
    spec:
      containers:
      - name: ftsbackendapp
        image: mybandscontainerregistry.azurecr.io/ftsbackendapp:latest
        ports:
        - containerPort: 8080