apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nsfeelthesteel
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mybandscontainerregistry.azurecr.io/ftsbackendapp:latest
        ports:
        - containerPort: 8080